flask_1/flaskshop/dashboard/__init__.py
from . import views  # noqa: F401

flask_1/flaskshop/dashboard/views/__init__.py
from . import bp  # noqa: F401

flask_1/flaskshop/dashboard/views/bp.py
from flask import Blueprint
from flask_login import login_required
from pluggy import HookimplMarker

from flaskshop.account.utils import permission_required
from flaskshop.constant import Permission
from flaskshop.dashboard.models import DashboardMenu
from flaskshop.settings import Config

from .index import index
from .discount import (
    sales,
    sales_manage,
    sale_del,
    vouchers,
    vouchers_manage,
    voucher_del,
)
from .order import draft_order, order_detail, orders, send_order
from .product import (
    attributes,
    attributes_manage,
    attribute_del,
    categories,
    categories_manage,
    category_del,
    collections,
    collections_manage,
    collection_del,
    product_create_step1,
    product_detail,
    product_manage,
    product_del,
    product_types,
    product_types_manage,
    product_type_del,
    products,
    variant_manage,
    variant_del,
)
from .site import (
    config_index,
    dashboard_menus,
    dashboard_menus_manage,
    dashboard_menu_del,
    plugin_disable,
    plugin_enable,
    plugin_list,
    shipping_methods,
    shipping_methods_manage,
    shipping_methods_del,
    site_menus,
    site_menus_manage,
    site_menu_del,
    site_pages,
    site_pages_manage,
    site_page_del,
    site_setting,
)
from .user import address_edit, user, user_edit, user_del, users

impl = HookimplMarker("flaskshop")


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint(
        "dashboard", __name__, template_folder=Config.DASHBOARD_TEMPLATE_FOLDER
    )

    @bp.context_processor
    def inject_param():
        menus = DashboardMenu.first_level_items()
        return {"menus": menus}

    @bp.before_request
    @permission_required(Permission.EDITOR)
    @login_required
    def before_request():
        """The whole blueprint need to login first"""
        pass

    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/site_menus", view_func=site_menus)
    bp.add_url_rule(
        "/site_menus/create", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_menus/<id>/edit", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_menus/<int:id>/delete", view_func=site_menu_del, methods=["DELETE"]
    )
    bp.add_url_rule("/dashboard_menus", view_func=dashboard_menus)
    bp.add_url_rule(
        "/dashboard_menus/create",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/dashboard_menus/<id>/edit",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/dashboard_menus/<int:id>/delete",
        view_func=dashboard_menu_del,
        methods=["DELETE"],
    )
    bp.add_url_rule("/site_pages", view_func=site_pages)
    bp.add_url_rule(
        "/site_pages/create", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_pages/<id>/edit", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_pages/<int:id>/delete", view_func=site_page_del, methods=["DELETE"]
    )
    bp.add_url_rule(
        "/site_setting/edit", view_func=site_setting, methods=["GET", "POST"]
    )
    bp.add_url_rule("/plugin", view_func=plugin_list)
    bp.add_url_rule("/plugin/<id>/enable", view_func=plugin_enable, methods=["POST"])
    bp.add_url_rule("/plugin/<id>/disable", view_func=plugin_disable, methods=["POST"])
    bp.add_url_rule("/config", view_func=config_index)
    bp.add_url_rule("/users", view_func=users)
    bp.add_url_rule("/users/<user_id>", view_func=user)
    bp.add_url_rule(
        "/users/<user_id>/edit", view_func=user_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule("/users/<int:id>/delete", view_func=user_del, methods=["DELETE"])
    bp.add_url_rule(
        "/users/address/<id>/edit", view_func=address_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule("/attributes", view_func=attributes)
    bp.add_url_rule(
        "/attributes/create", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/attributes/<id>/edit", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/attributes/<int:id>/delete", view_func=attribute_del, methods=["DELETE"]
    )
    bp.add_url_rule("/collections", view_func=collections)
    bp.add_url_rule(
        "/collections/create", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/collections/<id>/edit", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/collections/<int:id>/delete", view_func=collection_del, methods=["DELETE"]
    )
    bp.add_url_rule("/categories", view_func=categories)
    bp.add_url_rule(
        "/categories/create", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/categories/<id>/edit", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/categories/<int:id>/delete", view_func=category_del, methods=["DELETE"]
    )
    bp.add_url_rule("/product_types", view_func=product_types)
    bp.add_url_rule(
        "/product_types/create", view_func=product_types_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/product_types/<id>/edit",
        view_func=product_types_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/product_types/<int:id>/delete", view_func=product_type_del, methods=["DELETE"]
    )
    bp.add_url_rule("/shipping_methods", view_func=shipping_methods)
    bp.add_url_rule(
        "/shipping_methods/create",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/shipping_methods/<id>/edit",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/shipping_methods/<int:id>/delete",
        view_func=shipping_methods_del,
        methods=["DELETE"],
    )
    bp.add_url_rule("/products", view_func=products)
    bp.add_url_rule("/products/<id>", view_func=product_detail)
    bp.add_url_rule(
        "/products/create/step1",
        view_func=product_create_step1,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/create/step2",
        view_func=product_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/<id>/edit", view_func=product_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/<int:id>/delete", view_func=product_del, methods=["DELETE"]
    )
    bp.add_url_rule(
        "/products/variant/create", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/variant/<id>/edit", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/variants/<int:id>/delete", view_func=variant_del, methods=["DELETE"]
    )
    bp.add_url_rule("/orders", view_func=orders)
    bp.add_url_rule("/orders/<id>", view_func=order_detail)
    bp.add_url_rule("/orders/<id>/send", view_func=send_order)
    bp.add_url_rule("/orders/<id>/draft", view_func=draft_order)
    bp.add_url_rule("/vouchers", view_func=vouchers)
    bp.add_url_rule(
        "/vouchers/create", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/vouchers/<id>/edit", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/vouchers/<int:id>/delete", view_func=voucher_del, methods=["DELETE"]
    )
    bp.add_url_rule("/sales", view_func=sales)
    bp.add_url_rule("/sales/create", view_func=sales_manage, methods=["GET", "POST"])
    bp.add_url_rule("/sales/<id>/edit", view_func=sales_manage, methods=["GET", "POST"])
    bp.add_url_rule("/sales/<int:id>/delete", view_func=sale_del, methods=["DELETE"])

    app.register_blueprint(bp, url_prefix="/dashboard")

flask_1/flaskshop/dashboard/views/discount.py
from flask import redirect, render_template, request, url_for, flash
from flask_babel import lazy_gettext

from flaskshop.constant import DiscountValueTypeKinds, VoucherTypeKinds
from flaskshop.dashboard.forms import SaleForm, VoucherForm
from flaskshop.dashboard.utils import wrap_partial, item_del
from flaskshop.discount.models import Sale, Voucher
from flaskshop.product.models import Category, Product


def vouchers():
    page = request.args.get("page", type=int, default=1)
    pagination = Voucher.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "type_human": lazy_gettext("Type"),
        "usage_limit": lazy_gettext("Usage Limit"),
        "used": lazy_gettext("Used"),
        "discount_value_type_human": lazy_gettext("Discount Type"),
        "discount_value": lazy_gettext("Discount Value"),
    }
    context = {
        "title": lazy_gettext("Voucher"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": lazy_gettext("vouchers"),
    }
    return render_template("dashboard/general_list.html", **context)


def vouchers_manage(id=None):
    if id:
        voucher = Voucher.get_by_id(id)
        form = VoucherForm(obj=voucher)
    else:
        voucher = Voucher()
        form = VoucherForm()

    form.product_id.choices = [(p.id, p.title) for p in Product.query.all()]
    form.category_id.choices = [(c.id, c.title) for c in Category.query.all()]
    form.discount_value_type.choices = [
        (k.value, k.name) for k in DiscountValueTypeKinds
    ]
    form.type_.choices = [(k.value, k.name) for k in VoucherTypeKinds]

    if form.validate_on_submit():
        form.populate_obj(voucher)
        voucher.save()
        flash(lazy_gettext("Voucher saved."), "success")
        return redirect(url_for("dashboard.vouchers"))

    context = {"form": form, "title": lazy_gettext("Voucher")}
    return render_template("general_edit.html", **context)


voucher_del = wrap_partial(item_del, Voucher)


def sales():
    page = request.args.get("page", type=int, default=1)
    pagination = Sale.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "discount_value_type_label": lazy_gettext("Discount Type"),
        "discount_value": lazy_gettext("Discount Value"),
    }
    context = {
        "title": lazy_gettext("Sale"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": lazy_gettext("sales"),
    }
    return render_template("dashboard/general_list.html", **context)


def sales_manage(id=None):
    if id:
        sale = Sale.get_by_id(id)
        form = SaleForm(obj=sale)
    else:
        sale = Sale()
        form = SaleForm()

    form.products_ids.choices = [(p.id, p.title) for p in Product.query.all()]
    form.categories_ids.choices = [(c.id, c.title) for c in Category.query.all()]
    form.discount_value_type.choices = [
        (k.value, k.name) for k in DiscountValueTypeKinds
    ]

    if form.validate_on_submit():
        tmp_p = form.products_ids.data
        tmp_c = form.categories_ids.data
        del form.products_ids
        del form.categories_ids
        form.populate_obj(sale)
        sale.save()
        sale.update_products(tmp_p)
        sale.update_categories(tmp_c)
        flash(lazy_gettext("Sale saved."), "success")
        return redirect(url_for("dashboard.sales"))

    context = {"form": form, "title": lazy_gettext("Sale")}
    return render_template("general_edit.html", **context)


sale_del = wrap_partial(item_del, Sale)

flask_1/flaskshop/dashboard/views/index.py
from datetime import datetime

from sqlalchemy import func
from flask import render_template

from flaskshop.account.models import User
from flaskshop.constant import OrderEvents, OrderStatusKinds
from flaskshop.extensions import db
from flaskshop.order.models import Order, OrderEvent, OrderLine
from flaskshop.product.models import Product


def index():
    def get_today_num(model):
        target = db.cast(datetime.now(), db.DATE)
        which = db.cast(model.created_at, db.DATE)
        return model.query.filter(which == target).count()

    def get_order_status(status):
        return {
            "count": Order.query.filter_by(status=status).count(),
            "kind": status,
        }

    onsale_products_count = Product.query.filter_by(on_sale=True).count()

    hot_product_ids = (
        db.session.query(OrderLine.product_id, func.count(OrderLine.product_id))
        .group_by(OrderLine.product_id)
        .order_by(func.count(OrderLine.product_id).desc())
        .all()
    )
    top5_products = []
    for product_id, order_count in hot_product_ids[:5]:
        p = Product.get_by_id(product_id)
        # product may deleted
        if not p:
            continue
        p.order_count = order_count
        top5_products.append(p)

    activity = OrderEvent.query.order_by(OrderEvent.id.desc()).limit(10)

    context = {
        "orders_total": Order.query.count(),
        "orders_today": get_today_num(Order),
        "users_total": User.query.count(),
        "users_today": get_today_num(User),
        "order_unfulfill": get_order_status(OrderStatusKinds.unfulfilled.value),
        "order_fulfill": get_order_status(OrderStatusKinds.fulfilled.value),
        "onsale_products_count": onsale_products_count,
        "top_products": top5_products,
        "activity": activity,
        "order_events": OrderEvents,
    }
    return render_template("index.html", **context)

flask_1/flaskshop/dashboard/views/order.py
from flask import render_template, request, flash
from flask_babel import lazy_gettext

from flaskshop.constant import OrderStatusKinds
from flaskshop.order.models import Order


def orders():
    page = request.args.get("page", type=int, default=1)
    query = Order.query.order_by(Order.id.desc())

    status = request.args.get("status", type=int)
    if status:
        query = query.filter_by(status=status)
    order_no = request.args.get("order_number", type=str)
    if order_no:
        query = query.filter(Order.token.like(f"%{order_no}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        query = query.filter(Order.created_at >= created_at)
    ended_at = request.args.get("ended_at", type=str)
    if ended_at:
        query = query.filter(Order.created_at <= ended_at)
    pagination = query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "identity": lazy_gettext("Identity"),
        "status_human": lazy_gettext("Status"),
        "total_human": lazy_gettext("Total"),
        "user": lazy_gettext("User"),
        "created_at": lazy_gettext("Created At"),
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "order_stats_kinds": OrderStatusKinds,
    }
    return render_template("order/list.html", **context)


def order_detail(id):
    order = Order.get_by_id(id)
    return render_template("order/detail.html", order=order)


def send_order(id):
    order = Order.get_by_id(id)
    order.delivered()
    flash(lazy_gettext("Order is sent."), "success")
    return render_template("order/detail.html", order=order)


def draft_order(id):
    order = Order.get_by_id(id)
    order.draft()
    flash(lazy_gettext("Order is draft."), "success")
    return render_template("order/detail.html", order=order)

flask_1/flaskshop/order/__init__.py
from . import views  # noqa: F401

flask_1/flaskshop/order/payment/__init__.py
from . import zhifubao  # noqa: F401

flask_1/flaskshop/templates/dashboard/order/detail.html
{% extends 'dashboard/layout.html' %}

{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="invoice p-3 mb-3">
                    <!-- title row -->
                    <div class="row">
                        <div class="col-12">
                            <h4>
                                <i class="fa fa-globe"></i> {{order.token}}
                                <small class="float-right">{% trans %}Created At{% endtrans %}: {{order.created_at}}</small>
                            </h4>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- info row -->
                    <div class="row invoice-info">
                        <div class="col-sm-4 invoice-col">
                            <b>{% trans %}Status{% endtrans %}:</b> {{order.status_human}}<br>
                            <b>{% trans %}Payment Status{% endtrans %}:</b> {{order.payment.status_human}}<br>
                            <b>{% trans %}Payment Due{% endtrans %}:</b> {{order.payment.paid_at}}<br>
                            <b>{% trans %}Account{% endtrans %}:</b> {{order.user}}
                        </div>
                        <!-- /.col -->
                        <div class="col-sm-4 invoice-col">
                            <strong>{% trans %}Shipping Address{% endtrans %}</strong>
                            <address>
                                {{order.shipping_address | safe}}
                            </address>
                        </div>
                        <div class="col-sm-4 invoice-col">
                            <strong>{% trans %}Shipping Method{% endtrans %}</strong>
                            <address>
                                {{order.shipping_method_name}} (${{order.shipping_price_net}})
                            </address>
                        </div>
                    </div>
                    <!-- /.row -->

                    <!-- Table row -->
                    <div class="row">
                        <div class="col-12 table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>{% trans %}Qty{% endtrans %}</th>
                                        <th>{% trans %}Product{% endtrans %}</th>
                                        <th>{% trans %}SKU{% endtrans %}</th>
                                        <th>{% trans %}Unit Price{% endtrans %}</th>
                                        <th>{% trans %}Subtotal){% endtrans %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in order.lines %}
                                    <tr>
                                        <td>{{item.quantity}}</td>
                                        <td>
                                            <a href="{{url_for('dashboard.product_detail', id=item.product_id)}}"
                                                target="_blank">
                                                {{item.product_name}}
                                            </a>
                                        </td>
                                        <td>{{item.product_sku}}</td>
                                        <td>${{item.unit_price_net}}</td>
                                        <td>${{item.quantity * item.unit_price_net}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row">
                        <!-- accepted payments column -->
                        <div class="col-6">
                            <p class="lead">{% trans %}Payment Method{% endtrans %}: {{order.payment.payment_method}}</p>
                            <p class="lead">{% trans %}Order Note{% endtrans %}:</p>
                            <p class="text-muted">
                                {{order.note.content}}
                            </p>
                        </div>
                        <!-- /.col -->
                        <div class="col-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th class="w-50">{% trans %}Subtotal{% endtrans %}:</th>
                                        <td>${{order.total_net}}</td>
                                    </tr>
                                    <tr>
                                        <th>{% trans %}Shipping{% endtrans %}:</th>
                                        <td>${{order.shipping_price_net}}</td>
                                    </tr>

                                    <tr>
                                        <th>{% trans %}Discount{% endtrans %}:</th>
                                        <td>-${{ order.discount_amount  }}({{ order.discount_name }})</td>
                                    </tr>

                                    <tr>
                                        <th>{% trans %}Total{% endtrans %}:</th>
                                        <td>${{order.total}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->

                    <div class="row no-print">
                        <div class="col-12">
                            {% if order.status_human == "fulfilled" %}
                            <a class="btn btn-success float-right"
                                href="{{url_for('dashboard.send_order', id=order.id)}}">
                                <i class="fa fa-credit-card"></i> {% trans %}Send Order{% endtrans %}
                            </a>
                            {% elif order.status_human == "unfulfilled" %}
                            <a class="btn btn-danger float-right"
                                href="{{url_for('dashboard.draft_order', id=order.id)}}">
                                <i class="fa fa-ban"></i>{% trans %}Draft Order{% endtrans %}
                            </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
{% endblock %}

flask_1/flaskshop/templates/dashboard/order/list.html
{% extends 'dashboard/layout.html' %}
{% from 'bootstrap5/pagination.html' import render_pagination %}

{% block body %}
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">{% trans %}Order List{% endtrans %}</h4>
                            <div class="card-tools">
                                <form>
                                    <div class="row">
                                        <div class="form-group col-2">
                                            <select class="form-control form-control-sm" name="status">
                                                <option value="" disabled selected hidden>{% trans %}
                                                    Status{% endtrans %}</option>
                                                {% for stat in order_stats_kinds %}
                                                    <option value="{{ stat.value }}">{{ stat.name }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group col-2">
                                            <input type="text" name="order_number" class="form-control form-control-sm"
                                                   placeholder="{% trans %}Order No.{% endtrans %}">
                                        </div>
                                        <div class="form-group col-3">
                                            <input type="datetime-local" name="created_at" class="form-control form-control-sm"
                                                   placeholder="{% trans %}Created At{% endtrans %}" id="reservation">
                                        </div>
                                        <div class="form-group col-3">
                                            <input type="datetime-local" name="ended_at" class="form-control form-control-sm"
                                                   placeholder="{% trans %}Ended At{% endtrans %}" id="reservation">
                                        </div>
                                        <div class="form-group col-2">
                                            <button type="submit" class="btn btn-secondary btn-sm">{% trans %}
                                                Query{% endtrans %}</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="card-body table-responsive p-3">
                            <table class="table table-hover">
                                <tr>
                                    {% for th in props.values() %}
                                        <th>{{ th }}</th>
                                    {% endfor %}
                                    <th>{% trans %}Operation{% endtrans %}</th>
                                </tr>
                                {% for item in items %}
                                    <tr>
                                        {% for prop in props.keys() %}
                                            <td>{{ item | attr(prop) }}</td>
                                        {% endfor %}
                                        <td>
                                            <a href="{{ url_for('dashboard.order_detail', id=item.id) }}"
                                               class="btn btn-info btn-sm">{% trans %}View{% endtrans %}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                        {% if pagination.pages > 1 %}
                            <div class="card-footer clearfix">
                                {{ render_pagination(pagination, size='sm', align='right') }}
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}