flask_1/flaskshop/checkout/models.py
from flask import flash
from flask_login import current_user

from flaskshop.corelib.mc import cache, rdb
from flaskshop.database import Column, Model, db
from flaskshop.discount.models import Voucher
from flaskshop.product.models import ProductVariant

MC_KEY_CART_BY_USER = "checkout:cart:user_id:{}"


class Cart(Model):
    __tablename__ = "checkout_cart"
    user_id = Column(db.Integer())
    voucher_code = Column(db.String(255))
    quantity = Column(db.Integer())
    shipping_address_id = Column(db.Integer())
    shipping_method_id = Column(db.Integer())

    @property
    def subtotal(self):
        return sum(line.subtotal for line in self)

    @property
    def total(self):
        return self.subtotal + self.shipping_method_price - self.discount_amount

    @property
    def discount_amount(self):
        return self.voucher.get_vouchered_price(self) if self.voucher_code else 0

    @property
    def lines(self):
        return CartLine.query.filter(CartLine.cart_id == self.id).all()

    @classmethod
    @cache(MC_KEY_CART_BY_USER.format("{user_id}"))
    def get_cart_by_user_id(cls, user_id):
        return cls.query.filter_by(user_id=user_id).first()

    @classmethod
    def get_current_user_cart(cls):
        if current_user.is_authenticated:
            cart = cls.get_cart_by_user_id(current_user.id)
        else:
            cart = None
        return cart

    @classmethod
    def add_to_currentuser_cart(cls, quantity, variant_id):
        cart = cls.get_current_user_cart()
        variant = ProductVariant.get_by_id(variant_id)
        result, msg = variant.check_enough_stock(quantity)
        if result is False:
            flash(msg, "warning")
            return
        if cart:
            cart.quantity += quantity
            cart.save()
        else:
            cart = cls.create(user_id=current_user.id, quantity=quantity)
        line = CartLine.query.filter_by(cart_id=cart.id, variant_id=variant_id).first()
        if line:
            quantity += line.quantity
            line.update(quantity=quantity)
        else:
            CartLine.create(variant_id=variant_id, quantity=quantity, cart_id=cart.id)

    def get_product_price(self, product_id):
        price = 0
        for line in self:
            if line.product.id == product_id:
                price += line.subtotal
        return price

    def get_category_price(self, category_id):
        price = 0
        for line in self:
            if line.category.id == category_id:
                price += line.subtotal
        return price

    @property
    def is_shipping_required(self):
        return any(line.is_shipping_required for line in self)

    @property
    def shipping_method(self):
        return ShippingMethod.get_by_id(self.shipping_method_id)

    @property
    def shipping_method_price(self):
        if self.shipping_method:
            return self.shipping_method.price
        return 0

    @property
    def voucher(self):
        if self.voucher_code:
            return Voucher.get_by_code(self.voucher_code)
        return None

    def __repr__(self):
        return f"Cart(quantity={self.quantity})"

    def __iter__(self):
        return iter(self.lines)

    def __len__(self):
        return len(self.lines)

    def update_quantity(self):
        self.quantity = sum(line.quantity for line in self)
        if self.quantity == 0:
            self.delete()
        else:
            self.save()
        return self.quantity

    @classmethod
    def __flush_insert_event__(cls, target):
        rdb.delete(MC_KEY_CART_BY_USER.format(current_user.id))

    @classmethod
    def __flush_after_update_event__(cls, target):
        super().__flush_after_update_event__(target)
        rdb.delete(MC_KEY_CART_BY_USER.format(current_user.id))

    @classmethod
    def __flush_delete_event__(cls, target):
        super().__flush_delete_event__(target)
        rdb.delete(MC_KEY_CART_BY_USER.format(current_user.id))


class CartLine(Model):
    __tablename__ = "checkout_cartline"
    cart_id = Column(db.Integer())
    quantity = Column(db.Integer())
    variant_id = Column(db.Integer())

    def __repr__(self):
        return f"CartLine(variant={self.variant}, quantity={self.quantity})"

    @property
    def is_shipping_required(self):
        return self.variant.is_shipping_required

    @property
    def variant(self):
        return ProductVariant.get_by_id(self.variant_id)

    @property
    def product(self):
        return self.variant.product

    @property
    def category(self):
        return self.product.category

    @property
    def subtotal(self):
        return self.variant.price * self.quantity


class ShippingMethod(Model):
    __tablename__ = "checkout_shippingmethod"
    title = Column(db.String(255), nullable=False)
    price = Column(db.DECIMAL(10, 2))

    def __str__(self):
        return self.title + "   $" + str(self.price)

    @property
    def price_human(self):
        return "$" + str(self.price)

flask_1/flaskshop/checkout/forms.py
from flask_babel import lazy_gettext
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField


class NoteForm(FlaskForm):
    note = TextAreaField(lazy_gettext("ADD A NOTE TO YOUR ORDER"))


class VoucherForm(FlaskForm):
    code = StringField(lazy_gettext("Code"))

flask_1/flaskshop/checkout/__init__.py
from . import views  # noqa: F401

flask_1/flaskshop/checkout/views.py
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from flask_babel import lazy_gettext
from flask_login import current_user, login_required
from pluggy import HookimplMarker

from flaskshop.account.forms import AddressForm
from flaskshop.account.models import UserAddress
from flaskshop.discount.models import Voucher
from flaskshop.order.models import Order
from flaskshop.utils import flash_errors

from .forms import NoteForm, VoucherForm
from .models import Cart, CartLine, ShippingMethod

impl = HookimplMarker("flaskshop")


def cart_index():
    return render_template("checkout/cart.html")


def update_cartline(id):
    # TODO when not enough stock, response ajax error
    line = CartLine.get_by_id(id)
    response = {
        "variantId": line.variant_id,
        "subtotal": 0,
        "total": 0,
        "cart": {"numItems": 0, "numLines": 0},
    }
    if request.form["quantity"] == "0":
        line.delete()
    else:
        line.quantity = int(request.form["quantity"])
        line.save()
    cart = Cart.query.filter(Cart.user_id == current_user.id).first()
    response["cart"]["numItems"] = cart.update_quantity()
    response["cart"]["numLines"] = len(cart)
    response["subtotal"] = "$" + str(line.subtotal)
    response["total"] = "$" + str(cart.total)
    return jsonify(response)


def checkout_shipping():
    form = AddressForm(request.form)
    user_address = None
    if request.method == "POST":
        if request.form["address_sel"] != "new":
            user_address = UserAddress.get_by_id(request.form["address_sel"])
        elif request.form["address_sel"] == "new" and form.validate_on_submit():
            user_address = UserAddress.create(
                province=form.province.data,
                city=form.city.data,
                district=form.district.data,
                address=form.address.data,
                contact_name=form.contact_name.data,
                contact_phone=form.contact_phone.data,
                user_id=current_user.id,
            )
        shipping_method = ShippingMethod.get_by_id(request.form["shipping_method"])
        if user_address and shipping_method:
            cart = Cart.get_current_user_cart()
            cart.update(
                shipping_address_id=user_address.id,
                shipping_method_id=shipping_method.id,
            )
            return redirect(url_for("checkout.checkout_note"))
    flash_errors(form)
    shipping_methods = ShippingMethod.query.all()
    return render_template(
        "checkout/shipping.html", form=form, shipping_methods=shipping_methods
    )


def checkout_note():
    form = NoteForm(request.form)
    voucher_form = VoucherForm(request.form)
    cart = Cart.get_current_user_cart()
    address = (
        UserAddress.get_by_id(cart.shipping_address_id)
        if cart.shipping_address_id
        else None
    )
    shipping_method = (
        ShippingMethod.get_by_id(cart.shipping_method_id)
        if cart.shipping_method_id
        else None
    )
    if form.validate_on_submit():
        order, msg = Order.create_whole_order(cart, form.note.data)
        if order:
            return redirect(order.get_absolute_url())
        else:
            flash(msg, "warning")
            return redirect(url_for("checkout.cart_index"))
    return render_template(
        "checkout/note.html",
        form=form,
        address=address,
        voucher_form=voucher_form,
        shipping_method=shipping_method,
    )


def checkout_voucher():
    voucher_form = VoucherForm(request.form)
    if voucher_form.validate_on_submit():
        voucher = Voucher.get_by_code(voucher_form.code.data)
        cart = Cart.get_current_user_cart()
        err_msg = None
        if voucher:
            try:
                voucher.check_available(cart)
            except Exception as e:
                err_msg = str(e)
        else:
            err_msg = lazy_gettext("Your code is not correct")
        if err_msg:
            flash(err_msg, "warning")
        else:
            cart.voucher_code = voucher.code
            cart.save()
        return redirect(url_for("checkout.checkout_note"))


def checkout_voucher_remove():
    voucher_form = VoucherForm(request.form)
    if voucher_form.validate_on_submit():
        cart = Cart.get_current_user_cart()
        cart.voucher_code = None
        cart.save()
        return redirect(url_for("checkout.checkout_note"))


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint("checkout", __name__)

    @bp.before_request
    @login_required
    def before_request():
        """The whole blueprint need to login first"""
        pass

    bp.add_url_rule("/cart", view_func=cart_index)
    bp.add_url_rule(
        "/update_cart/<int:id>", view_func=update_cartline, methods=["POST"]
    )
    bp.add_url_rule("/shipping", view_func=checkout_shipping, methods=["GET", "POST"])
    bp.add_url_rule("/note", view_func=checkout_note, methods=["GET", "POST"])
    bp.add_url_rule("/voucher", view_func=checkout_voucher, methods=["POST"])
    bp.add_url_rule(
        "/voucher/remove", view_func=checkout_voucher_remove, methods=["POST"]
    )

    app.register_blueprint(bp, url_prefix="/checkout")

flask_1/flaskshop/templates/checkout/_subtotal_table.html
<div class="cart__total">
  <div class="row">
    <div class="col-8 cart__total__subtotal">
      <h3>{% trans %}Total{% endtrans %}</h3>
      <small>{% trans %}Shipment calculated at checkout{% endtrans %}</small>
    </div>
    <div class="col-4">
      <h3 class="text-right cart-total"><span>${{ current_user_cart.total }}</span></h3>
    </div>
  </div>
</div>

flask_1/flaskshop/templates/checkout/cart.html
{% extends "no_nav_base.html" %}

{% block title %}{% trans %}Your cart{% endtrans %}{% endblock %}

{% block breadcrumb %}
<ul class="breadcrumbs list-unstyled">
    <li><a href="{{ url_for('public.home') }}">{% trans %}Home{% endtrans %}</a></li>
    <li><a rel="nofollow" href="">{% trans %}Cart{% endtrans %}</a></li>
</ul>
{% endblock breadcrumb %}


{% block content %}
<div class="alert alert-success alert-dismissible fade remove-product-alert show d-none" role="alert">
    <span contenteditable="true">{% trans %}Product has been removed from cart{% endtrans %}</span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<div class="cart">
    {% if current_user_cart.lines %}
    <div class="table__header d-none d-md-block">
        <div class="row">
            <div class="col-md-7">
                <small>{% trans %}Product{% endtrans %}</small>
            </div>
            <div class="col-md-3">
                <small>{% trans %}Quantity{% endtrans %}</small>
            </div>
            <div class="col-md-2 text-right">
                <small>{% trans %}Price{% endtrans %}</small>
            </div>
        </div>
    </div>
    {% for line in current_user_cart.lines %}
    <div class="cart__line{% if loop.last %} last{% endif %} table__row">
        <div class="row">
            <div class="col-7 cart__line__product">
                <a class="link--clean" href="{{ line.product.get_absolute_url() }}">
                    <img class="lazyload lazypreload" data-src="{{ line.product.first_img }}" width="60" />
                    <p>{{ line.product }}<br>
                        <small>{{ line.variant }}</small>
                    </p>
                </a>
            </div>
            <div class="col-5">
                <div class="row">
                    <div class="cart__line__quantity col-md-7 col-12">
                        <form action="{{ url_for('checkout.update_cartline', id=line.id) }}" class="form-cart">
                            <div class="" tabindex="-1">
                                <input type="number" value="{{ line.quantity }}" min="1" max="50" id="id_quantity">
                            </div>
                        </form>
                        <span class="cart-item-delete">
                            <svg data-src="{{ url_for('static', filename='img/delete.svg') }}" height="20px"
                                width="20px"></svg>
                        </span>
                        <small class="cart__line__quantity-error text-danger"></small>
                    </div>
                    <div class="cart-item-price col-md-5 col-12" data-product-id="{{ line.variant.id }}">
                        <p class="text-right">
                            $ {{ line.subtotal }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="cart__subtotal">
        {% include 'checkout/_subtotal_table.html' %}
    </div>
    <div class="row">
        <div class="col-md-12">
            <a href="{% if current_user_cart.is_shipping_required %}{{ url_for('checkout.checkout_shipping') }}{% else %}{{ url_for('checkout.checkout_note') }}{% endif %}"
                class="btn btn-primary float-right cart__submit">
                {% trans %}Checkout{% endtrans %}
            </a>
        </div>
    </div>
    {% else %}
    <div class="cart__empty">
        <img class="lazyload lazypreload" data-src="{{ url_for('static', filename='img/empty-cart-bg.png') }}"
            title="empty">
        <h2>{% trans %}There are no products in your shopping cart.{% endtrans %}</h2>
        <a href="{{ url_for('public.home') }}" class="btn btn-primary">{% trans %}Check out our sales{% endtrans %}</a>
    </div>
    {% endif %}
</div>
{% endblock content %}

flask_1/flaskshop/templates/checkout/details.html
{% extends "base.html" %}

{% block title %}{% trans %}Checkout{% endtrans %}{% endblock %}

{% block header %}
<div class="container-fluid navbar__login">
  <div class="container">
    <p>{% trans %}Easy and secure!{% endtrans %}</p>
  </div>
</div>
<header class="checkout__header">
  <div class="container">
    <a href="{{ url_for('public.home') }}">
      <svg data-src="{{ url_for('static', filename='img/logo-document.svg') }}" height="48px" width="176px"></svg>
    </a>
    <h1>{% trans %}Checkout{% endtrans %}</h1>
  </div>
</header>
{% endblock %}

{% block footer %}
{% endblock %}

{% block content %}
<div class="row checkout">
  <div class="col-md-7">
    {% block forms %}{% endblock %}
  </div>
  <div class="col-md-5">
    <div class="checkout__review">
      <h3 class="checkout__review__tittle">Order review</h3>
      {% for line in current_user_cart.lines %}
      <div class="row">
        <div class="col-8">
          <p><strong>{{ line.variant.product }}</strong> x {{ line.quantity }}<br>
            <span class="checkout__review__variant">{{ line.variant }}</span>
          </p>
        </div>
        <div class="col-4">
          <p class="float-right">
            ${{ line.subtotal }}
          </p>
        </div>
      </div>
      {% endfor %}
      <div class="row checkout__review__section">
        <div class="col-8">
          <p>{% trans %}Subtotal{% endtrans %}</p>
        </div>
        <div class="col-4">
          <p class="float-right">
            ${{ current_user_cart.subtotal }}
          </p>
        </div>
      </div>
      <div class="row checkout__review__section">
        <div class="col-8">
          <p>{% trans %}Shipment{% endtrans %}</p>
        </div>
        <div class="col-4">
          <p class="float-right">
            {% if current_user_cart.shipping_method %}
            ${{current_user_cart.shipping_method_price }}
            {% else %}
            &mdash;
            {% endif %}
          </p>
        </div>
      </div>
      {% if voucher_form %}
      <div class="row checkout__review__section">
        <div class="col-12">
          <h3>{% trans %}Promo code{% endtrans %}</h3>
          {% if current_user_cart.voucher_code %}
          <form action="{{url_for('checkout.checkout_voucher_remove')}}" method="post" class="float-left input-btn">
            {{voucher_form.csrf_token}}
            <span>{{ current_user_cart.voucher.title }}</span>
            <button type="submit" class="btn btn-link btn-voucher-remove" aria-label=Remove">
              {% trans %}Remove{% endtrans %}
            </button>
          </form>
          <div class="float-right">
            -${{current_user_cart.discount_amount}}
          </div>
          {% else %}

          <form action="{{url_for('checkout.checkout_voucher')}}" method="post">
            {{voucher_form.csrf_token}}
            <div class="input-group mb-3">
              <input type="text" name="code" class="form-control" aria-label="voucher" aria-describedby="button-addon">
              <button class="btn secondary narrow" type="submit" id="button-addon">Use</button>
            </div>
          </form>
          {% endif %}
        </div>
      </div>
      {% endif %}
      <div class="row checkout__review__section">
        <div class="col-8">
          <h3>{% trans %}Total{% endtrans %}</h3>
        </div>
        <div class="col-4">
          <h3 class="float-right">${{ current_user_cart.total }}</h3>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

flask_1/flaskshop/templates/checkout/note.html
{% extends "checkout/details.html" %}
{% from 'bootstrap5/form.html' import render_field %}

{% block forms %}
{% if address %}
<div class="row">
  <div class="col-md-6">
    <h3>{% trans %}Shipping address{% endtrans %}</h3>
    {{ macros.format_address(address) }}
    <p><a href="{{ url_for('checkout.checkout_shipping') }}">{% trans %}Select other address{% endtrans %}</a></p>
  </div>
  <div class="col-md-6">
    <h3>Shipping Method</h3>
    {{ shipping_method }}
    <p><a href="{{ url_for('checkout.checkout_shipping') }}">{% trans %}Select other shipping method{% endtrans %}</a>
    </p>
  </div>
</div>
<hr>
{% endif %}


<form method="post" novalidate>
  {{ form.csrf_token }}
  {{ render_field(form.note) }}
  <p class="text-md-right">
    <button type="submit" class="btn btn-primary">
      ORDER & PAY
    </button>
  </p>
</form>
{% endblock %}

flask_1/flaskshop/templates/checkout/shipping.html
{% extends "checkout/details.html" %}
{% import '_macros.html' as macros %}
{% block forms %}
<form method="post" novalidate class="checkout__shipping">
  <div class="row">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="mb-1">
        <h2>{% trans %}Shipping address{% endtrans %}</h2>
      </div>

      {% for address in current_user.addresses %}
      <div class="radio address_hide">
        <label>
          <input type="radio" name="address_sel" value="{{ address.id }}" id="address_{{ address.id }}"
            {% if loop.first %}checked{%endif%} />
          <div class="address-details">
            {{ macros.format_address(address) }}
          </div>
        </label>
      </div>
      {% endfor %}

      <div class="radio address_show col-12 float-left">
        <label>
          <input type="radio" name="address_sel" value="new" id="address_new">
          {% trans %}Enter a new address{% endtrans %}
        </label>
      </div>


      <div class="checkout__new-address">
        <div class="address_show col-12 float-left">
          {% include "account/partials/address_form.html" %}
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-3">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="mb-1">
        <h2>{% trans %}Shipping method{% endtrans %}</h2>
      </div>
      {% for method in shipping_methods %}
      <div class="radio col-6 float-left">
        <label>
          <input type="radio" name="shipping_method" value="{{ method.id }}" id="shipping_{{ method.id }}"
            {% if loop.first %}checked{%endif%} />
          <div class="address-details">
            {{ method }}
          </div>
        </label>
      </div>
      {% endfor %}
    </div>
  </div>
  <p class="text-md-right">
    <button type="submit" class="btn btn-primary">
      {% trans %}Continue{% endtrans %}
    </button>
  </p>
</form>
{% endblock %}