flask_1/flaskshop/dashboard/models.py
from flask import request, url_for

from flaskshop.constant import SettingValueType
from flaskshop.database import Column, Model, db


class DashboardMenu(Model):
    __tablename__ = "management_dashboard"
    title = Column(db.String(255), nullable=False)
    order = Column(db.Integer(), default=0)
    endpoint = Column(db.String(255))
    icon_cls = Column(db.String(255))
    parent_id = Column(db.Integer(), default=0)

    def __str__(self):
        return self.title

    @property
    def children(self):
        return DashboardMenu.query.filter(DashboardMenu.parent_id == self.id).all()

    @classmethod
    def first_level_items(cls):
        return cls.query.filter(cls.parent_id == 0).order_by("order").all()

    def is_active(self):
        if self.endpoint and self.endpoint in request.path:
            return True
        if any((child.is_active() for child in self.children)):
            return True
        return False

    def get_url(self):
        if self.children:
            return "#"
        if self.endpoint:
            return url_for("dashboard." + self.endpoint)


class Setting(Model):
    __tablename__ = "management_setting"
    id = None
    key = Column(db.String(255), primary_key=True)
    value = Column(db.PickleType, nullable=False)
    name = Column(db.String(255), nullable=False)
    description = Column(db.Text, nullable=False)
    value_type = Column(db.Enum(SettingValueType), nullable=False)
    extra = Column(db.PickleType)

    @classmethod
    def get_settings(cls):
        settings = {}
        for s in cls.query.all():
            settings[s.key] = s.value
        return settings

    @classmethod
    def update(cls, settings):
        """Updates the cache and stores the changes in the
        database.
        :param settings: A dictionary with setting items.
        """
        # update the database
        for key, value in settings.items():
            setting = cls.query.filter(Setting.key == key.lower()).first()

            setting.value = value

            db.session.add(setting)
        db.session.commit()

    def __repr__(self):
        return f"<{self.__class__.__name__} {self.key}>"

flask_1/flaskshop/dashboard/__init__.py
from . import views  # noqa: F401

flask_1/flaskshop/dashboard/views/__init__.py
from . import bp  # noqa: F401

flask_1/flaskshop/dashboard/views/bp.py
from flask import Blueprint
from flask_login import login_required
from pluggy import HookimplMarker

from flaskshop.account.utils import permission_required
from flaskshop.constant import Permission
from flaskshop.dashboard.models import DashboardMenu
from flaskshop.settings import Config

from .index import index
from .discount import (
    sales,
    sales_manage,
    sale_del,
    vouchers,
    vouchers_manage,
    voucher_del,
)
from .order import draft_order, order_detail, orders, send_order
from .product import (
    attributes,
    attributes_manage,
    attribute_del,
    categories,
    categories_manage,
    category_del,
    collections,
    collections_manage,
    collection_del,
    product_create_step1,
    product_detail,
    product_manage,
    product_del,
    product_types,
    product_types_manage,
    product_type_del,
    products,
    variant_manage,
    variant_del,
)
from .site import (
    config_index,
    dashboard_menus,
    dashboard_menus_manage,
    dashboard_menu_del,
    plugin_disable,
    plugin_enable,
    plugin_list,
    shipping_methods,
    shipping_methods_manage,
    shipping_methods_del,
    site_menus,
    site_menus_manage,
    site_menu_del,
    site_pages,
    site_pages_manage,
    site_page_del,
    site_setting,
)
from .user import address_edit, user, user_edit, user_del, users

impl = HookimplMarker("flaskshop")


@impl
def flaskshop_load_blueprints(app):
    bp = Blueprint(
        "dashboard", __name__, template_folder=Config.DASHBOARD_TEMPLATE_FOLDER
    )

    @bp.context_processor
    def inject_param():
        menus = DashboardMenu.first_level_items()
        return {"menus": menus}

    @bp.before_request
    @permission_required(Permission.EDITOR)
    @login_required
    def before_request():
        """The whole blueprint need to login first"""
        pass

    bp.add_url_rule("/", view_func=index)
    bp.add_url_rule("/site_menus", view_func=site_menus)
    bp.add_url_rule(
        "/site_menus/create", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_menus/<id>/edit", view_func=site_menus_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_menus/<int:id>/delete", view_func=site_menu_del, methods=["DELETE"]
    )
    bp.add_url_rule("/dashboard_menus", view_func=dashboard_menus)
    bp.add_url_rule(
        "/dashboard_menus/create",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/dashboard_menus/<id>/edit",
        view_func=dashboard_menus_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/dashboard_menus/<int:id>/delete",
        view_func=dashboard_menu_del,
        methods=["DELETE"],
    )
    bp.add_url_rule("/site_pages", view_func=site_pages)
    bp.add_url_rule(
        "/site_pages/create", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_pages/<id>/edit", view_func=site_pages_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/site_pages/<int:id>/delete", view_func=site_page_del, methods=["DELETE"]
    )
    bp.add_url_rule(
        "/site_setting/edit", view_func=site_setting, methods=["GET", "POST"]
    )
    bp.add_url_rule("/plugin", view_func=plugin_list)
    bp.add_url_rule("/plugin/<id>/enable", view_func=plugin_enable, methods=["POST"])
    bp.add_url_rule("/plugin/<id>/disable", view_func=plugin_disable, methods=["POST"])
    bp.add_url_rule("/config", view_func=config_index)
    bp.add_url_rule("/users", view_func=users)
    bp.add_url_rule("/users/<user_id>", view_func=user)
    bp.add_url_rule(
        "/users/<user_id>/edit", view_func=user_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule("/users/<int:id>/delete", view_func=user_del, methods=["DELETE"])
    bp.add_url_rule(
        "/users/address/<id>/edit", view_func=address_edit, methods=["GET", "POST"]
    )
    bp.add_url_rule("/attributes", view_func=attributes)
    bp.add_url_rule(
        "/attributes/create", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/attributes/<id>/edit", view_func=attributes_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/attributes/<int:id>/delete", view_func=attribute_del, methods=["DELETE"]
    )
    bp.add_url_rule("/collections", view_func=collections)
    bp.add_url_rule(
        "/collections/create", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/collections/<id>/edit", view_func=collections_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/collections/<int:id>/delete", view_func=collection_del, methods=["DELETE"]
    )
    bp.add_url_rule("/categories", view_func=categories)
    bp.add_url_rule(
        "/categories/create", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/categories/<id>/edit", view_func=categories_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/categories/<int:id>/delete", view_func=category_del, methods=["DELETE"]
    )
    bp.add_url_rule("/product_types", view_func=product_types)
    bp.add_url_rule(
        "/product_types/create", view_func=product_types_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/product_types/<id>/edit",
        view_func=product_types_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/product_types/<int:id>/delete", view_func=product_type_del, methods=["DELETE"]
    )
    bp.add_url_rule("/shipping_methods", view_func=shipping_methods)
    bp.add_url_rule(
        "/shipping_methods/create",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/shipping_methods/<id>/edit",
        view_func=shipping_methods_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/shipping_methods/<int:id>/delete",
        view_func=shipping_methods_del,
        methods=["DELETE"],
    )
    bp.add_url_rule("/products", view_func=products)
    bp.add_url_rule("/products/<id>", view_func=product_detail)
    bp.add_url_rule(
        "/products/create/step1",
        view_func=product_create_step1,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/create/step2",
        view_func=product_manage,
        methods=["GET", "POST"],
    )
    bp.add_url_rule(
        "/products/<id>/edit", view_func=product_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/<int:id>/delete", view_func=product_del, methods=["DELETE"]
    )
    bp.add_url_rule(
        "/products/variant/create", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/products/variant/<id>/edit", view_func=variant_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/variants/<int:id>/delete", view_func=variant_del, methods=["DELETE"]
    )
    bp.add_url_rule("/orders", view_func=orders)
    bp.add_url_rule("/orders/<id>", view_func=order_detail)
    bp.add_url_rule("/orders/<id>/send", view_func=send_order)
    bp.add_url_rule("/orders/<id>/draft", view_func=draft_order)
    bp.add_url_rule("/vouchers", view_func=vouchers)
    bp.add_url_rule(
        "/vouchers/create", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/vouchers/<id>/edit", view_func=vouchers_manage, methods=["GET", "POST"]
    )
    bp.add_url_rule(
        "/vouchers/<int:id>/delete", view_func=voucher_del, methods=["DELETE"]
    )
    bp.add_url_rule("/sales", view_func=sales)
    bp.add_url_rule("/sales/create", view_func=sales_manage, methods=["GET", "POST"])
    bp.add_url_rule("/sales/<id>/edit", view_func=sales_manage, methods=["GET", "POST"])
    bp.add_url_rule("/sales/<int:id>/delete", view_func=sale_del, methods=["DELETE"])

    app.register_blueprint(bp, url_prefix="/dashboard")

flask_1/flaskshop/dashboard/views/discount.py
from flask import redirect, render_template, request, url_for, flash
from flask_babel import lazy_gettext

from flaskshop.constant import DiscountValueTypeKinds, VoucherTypeKinds
from flaskshop.dashboard.forms import SaleForm, VoucherForm
from flaskshop.dashboard.utils import wrap_partial, item_del
from flaskshop.discount.models import Sale, Voucher
from flaskshop.product.models import Category, Product


def vouchers():
    page = request.args.get("page", type=int, default=1)
    pagination = Voucher.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "type_human": lazy_gettext("Type"),
        "usage_limit": lazy_gettext("Usage Limit"),
        "used": lazy_gettext("Used"),
        "discount_value_type_human": lazy_gettext("Discount Type"),
        "discount_value": lazy_gettext("Discount Value"),
    }
    context = {
        "title": lazy_gettext("Voucher"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": lazy_gettext("vouchers"),
    }
    return render_template("dashboard/general_list.html", **context)


def vouchers_manage(id=None):
    if id:
        voucher = Voucher.get_by_id(id)
        form = VoucherForm(obj=voucher)
    else:
        voucher = Voucher()
        form = VoucherForm()

    form.product_id.choices = [(p.id, p.title) for p in Product.query.all()]
    form.category_id.choices = [(c.id, c.title) for c in Category.query.all()]
    form.discount_value_type.choices = [
        (k.value, k.name) for k in DiscountValueTypeKinds
    ]
    form.type_.choices = [(k.value, k.name) for k in VoucherTypeKinds]

    if form.validate_on_submit():
        form.populate_obj(voucher)
        voucher.save()
        flash(lazy_gettext("Voucher saved."), "success")
        return redirect(url_for("dashboard.vouchers"))

    context = {"form": form, "title": lazy_gettext("Voucher")}
    return render_template("general_edit.html", **context)


voucher_del = wrap_partial(item_del, Voucher)


def sales():
    page = request.args.get("page", type=int, default=1)
    pagination = Sale.query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "title": lazy_gettext("Title"),
        "discount_value_type_label": lazy_gettext("Discount Type"),
        "discount_value": lazy_gettext("Discount Value"),
    }
    context = {
        "title": lazy_gettext("Sale"),
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "identity": lazy_gettext("sales"),
    }
    return render_template("dashboard/general_list.html", **context)


def sales_manage(id=None):
    if id:
        sale = Sale.get_by_id(id)
        form = SaleForm(obj=sale)
    else:
        sale = Sale()
        form = SaleForm()

    form.products_ids.choices = [(p.id, p.title) for p in Product.query.all()]
    form.categories_ids.choices = [(c.id, c.title) for c in Category.query.all()]
    form.discount_value_type.choices = [
        (k.value, k.name) for k in DiscountValueTypeKinds
    ]

    if form.validate_on_submit():
        tmp_p = form.products_ids.data
        tmp_c = form.categories_ids.data
        del form.products_ids
        del form.categories_ids
        form.populate_obj(sale)
        sale.save()
        sale.update_products(tmp_p)
        sale.update_categories(tmp_c)
        flash(lazy_gettext("Sale saved."), "success")
        return redirect(url_for("dashboard.sales"))

    context = {"form": form, "title": lazy_gettext("Sale")}
    return render_template("general_edit.html", **context)


sale_del = wrap_partial(item_del, Sale)

flask_1/flaskshop/dashboard/views/index.py
from datetime import datetime

from sqlalchemy import func
from flask import render_template

from flaskshop.account.models import User
from flaskshop.constant import OrderEvents, OrderStatusKinds
from flaskshop.extensions import db
from flaskshop.order.models import Order, OrderEvent, OrderLine
from flaskshop.product.models import Product


def index():
    def get_today_num(model):
        target = db.cast(datetime.now(), db.DATE)
        which = db.cast(model.created_at, db.DATE)
        return model.query.filter(which == target).count()

    def get_order_status(status):
        return {
            "count": Order.query.filter_by(status=status).count(),
            "kind": status,
        }

    onsale_products_count = Product.query.filter_by(on_sale=True).count()

    hot_product_ids = (
        db.session.query(OrderLine.product_id, func.count(OrderLine.product_id))
        .group_by(OrderLine.product_id)
        .order_by(func.count(OrderLine.product_id).desc())
        .all()
    )
    top5_products = []
    for product_id, order_count in hot_product_ids[:5]:
        p = Product.get_by_id(product_id)
        # product may deleted
        if not p:
            continue
        p.order_count = order_count
        top5_products.append(p)

    activity = OrderEvent.query.order_by(OrderEvent.id.desc()).limit(10)

    context = {
        "orders_total": Order.query.count(),
        "orders_today": get_today_num(Order),
        "users_total": User.query.count(),
        "users_today": get_today_num(User),
        "order_unfulfill": get_order_status(OrderStatusKinds.unfulfilled.value),
        "order_fulfill": get_order_status(OrderStatusKinds.fulfilled.value),
        "onsale_products_count": onsale_products_count,
        "top_products": top5_products,
        "activity": activity,
        "order_events": OrderEvents,
    }
    return render_template("index.html", **context)

flask_1/flaskshop/dashboard/views/order.py
from flask import render_template, request, flash
from flask_babel import lazy_gettext

from flaskshop.constant import OrderStatusKinds
from flaskshop.order.models import Order


def orders():
    page = request.args.get("page", type=int, default=1)
    query = Order.query.order_by(Order.id.desc())

    status = request.args.get("status", type=int)
    if status:
        query = query.filter_by(status=status)
    order_no = request.args.get("order_number", type=str)
    if order_no:
        query = query.filter(Order.token.like(f"%{order_no}%"))
    created_at = request.args.get("created_at", type=str)
    if created_at:
        query = query.filter(Order.created_at >= created_at)
    ended_at = request.args.get("ended_at", type=str)
    if ended_at:
        query = query.filter(Order.created_at <= ended_at)
    pagination = query.paginate(page, 10)
    props = {
        "id": lazy_gettext("ID"),
        "identity": lazy_gettext("Identity"),
        "status_human": lazy_gettext("Status"),
        "total_human": lazy_gettext("Total"),
        "user": lazy_gettext("User"),
        "created_at": lazy_gettext("Created At"),
    }
    context = {
        "items": pagination.items,
        "props": props,
        "pagination": pagination,
        "order_stats_kinds": OrderStatusKinds,
    }
    return render_template("order/list.html", **context)


def order_detail(id):
    order = Order.get_by_id(id)
    return render_template("order/detail.html", order=order)


def send_order(id):
    order = Order.get_by_id(id)
    order.delivered()
    flash(lazy_gettext("Order is sent."), "success")
    return render_template("order/detail.html", order=order)


def draft_order(id):
    order = Order.get_by_id(id)
    order.draft()
    flash(lazy_gettext("Order is draft."), "success")
    return render_template("order/detail.html", order=order)

flask_1/flaskshop/templates/dashboard/index.html
{% extends 'dashboard/layout.html' %}

{% block body %}
    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="info-box mb-3">
                            <span class="info-box-icon bg-success"><i
                                    class="fa fa-shopping-cart"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">{% trans %}Sales{% endtrans %}</span>
                                    <span class="info-box-text"><b>{{ orders_today }}</b> {% trans %}today
                                        and{% endtrans %} <b>{{ orders_total }}</b>
                                        {% trans %}total{% endtrans %}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="info-box mb-3">
                                <span class="info-box-icon bg-warning"><i class="fa fa-users"></i></span>
                                <div class="info-box-content">
                                    <span class="info-box-text">{% trans %}Members{% endtrans %}</span>
                                    <span class="info-box-text"><b>{{ users_today }}</b> {% trans %}new in{% endtrans %}
                                        <b>{{ users_total }}</b>
                                        {% trans %}accounts{% endtrans %}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body p-0">
                            <ul class="navi-card">
                                <li class="item">
                                    <a href="{{ url_for('dashboard.orders', status=order_fulfill.kind) }}">
                                        <span>{{ order_fulfill.count }} {% trans %}Orders are ready to
                                            fulfill{% endtrans %}</span>
                                        <span class="right">></span>
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="{{ url_for('dashboard.orders', status=order_unfulfill.kind) }}">
                                        <span>{{ order_unfulfill.count }} {% trans %}Payments to
                                            capture{% endtrans %}</span>
                                        <span class="right">></span>
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="{{ url_for('dashboard.products', sale=True) }}">
                                        <span>{{ onsale_products_count }} {% trans %}products is on
                                            sale{% endtrans %}</span>
                                        <span class="right">></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-header">
                            <h6 class="card-title">{% trans %}Top Products{% endtrans %}</h6>
                        </div>
                        <div class="card-body p-0">
                            <ul class="products-list product-list-in-card px-2">
                                {% for product in top_products %}
                                    <li class="item">
                                        <img src="{{ product.first_img }}"
                                             alt="Product Image">
                                        <div class="product-info">
                                            <a href="{{ url_for('dashboard.product_detail', id=product.id) }}"
                                               class="product-title">{{ product.title }}
                                                <span class="badge text-bg-primary float-right">{{ product.price_human }}</span>
                                            </a>
                                            <span class="product-description">
                                                {{ product.description }}
                                            </span>
                                            <span class="product-description">
                                                {{ product.order_count }} {% trans %}Ordered{% endtrans %}
                                            </span>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h6 class="card-title">{% trans %}Activity{% endtrans %}</h6>
                        </div>
                        <div class="card-body p-0">
                            <ul class="activity product-list-in-card px-2">
                                {% for a in activity %}
                                    <li class="item">
                                        <span class="activity-title">{% trans %}Order{% endtrans %} #{{ a.order_id }}
                                            {% trans %}was{% endtrans %} {{ order_events(a.type_).name }}</span>
                                        <span>{{ a.created_at_human }}</span>
                                    </li>
                                {% else %}
                                    <li class="item">
                                        <span class="activity-title">{% trans %}There is no recent
                                            activity{% endtrans %} </span>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

flask_1/flaskshop/templates/dashboard/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Dashboard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="https://unpkg.com/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="https://unpkg.com/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
    <link href="https://unpkg.com/font-awesome@4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='dashboard/index.css') }}">
    {% block head_tail %}
    {% endblock %}
</head>

{% block page_body %}
    <body>
    <div>
        <nav class="main-header navbar navbar-expand border-bottom no-transition" id="header">
            <ul class="navbar-nav">
                <li>
                    <a class="nav-link" id="toggleSidebar" href="#" title="toggle"><i class="fa fa-bars"></i></a>
                </li>
                <li>
                    <a href="{{ url_for('dashboard.index') }}" class="nav-link">{% trans %}Dashboard{% endtrans %}</a>
                </li>
                <li>
                    <a href="{{ url_for('public.home') }}" class="nav-link" target="_blank">{% trans %}Front
                        Site{% endtrans %}</a>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar elevation-4">
            <a href="{{ url_for('dashboard.index') }}" class="brand-link">
                <img src="{{ url_for('static', filename='img/logo.svg') }}" class="brand-image" alt="logo">
            </a>

            <div class="sidebar">
                <div class="user-panel my-3">
                    <div class="image">
                        <img src="{{ current_user.avatar }}" class="rounded-circle" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#">{{ current_user.username }}</a>
                    </div>
                </div>
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column">
                        {%- for item in menus %}
                            <li class="has-treeview mt-2 {% if item.is_active() %}menu-open{% endif %}">
                                <a href="{{ item.get_url() }}"
                                   class="nav-link {%- if item.is_active() %} active{% endif %}">
                                    <i class="fa nav-icon {{ item.icon_cls }}"></i>
                                    <p>{{ item.title }}
                                        {%- if item.children %}<i class="right fa fa-angle-left"></i>{% endif %}
                                    </p>
                                </a>
                                {%- if item.children %}
                                    <ul class="nav nav-treeview">
                                        {%- for child in item.children -%}
                                            <li class="nav-item mt-2">
                                                <a href="{{ child.get_url() }}"
                                                   class="nav-link {%- if child.is_active() %} active{%- endif %}">
                                                    <i class="fa fa-circle-o nav-icon"></i>
                                                    <p>{{ child.title }}</p>
                                                </a>
                                            </li>
                                        {%- endfor %}
                                    </ul>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </nav>
            </div>
        </aside>

        <div class="content-wrapper no-transition" id="content">
            {% block body %} {% endblock %}
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Warning</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure to delete?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="confirmDelete">OK</button>
                </div>
            </div>
        </div>
    </div>
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="deleteToast" class="toast align-items-center text-bg-primary border-0" role="alert"
             aria-live="assertive"
             aria-atomic="true" data-bs-config='{"delay":1000}'>
            <div class="d-flex">
                <div class="toast-body">
                    Poof! This item has been deleted!
                </div>
                <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                        aria-label="Close"></button>
            </div>
        </div>
        {% for message in get_flashed_messages(with_categories=True) %}
            <div class="toast align-items-center text-bg-{{ message[0] }} border-0 msg-toast" role="alert"
                 aria-live="assertive"
                 aria-atomic="true" data-bs-config='{"delay":2500}'>
                <div class="d-flex">
                    <div class="toast-body">
                        {{ message[1] }}
                    </div>
                    <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                            aria-label="Close"></button>
                </div>
            </div>
        {% endfor %}
    </div>
    <script src="https://unpkg.com/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="https://unpkg.com/tom-select@2.2.2/dist/js/tom-select.base.min.js" defer></script>
    <script src="{{ url_for('static', filename='dashboard/index.js') }}" defer></script>
    {% block tail_js %} {% endblock %}
    </body>
{% endblock %}

</html>