django/lesson_1/lesson_1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')), # пути нашего приложения
]

django/lesson_1/myapp/urls.py
from django.urls import path 
# from . import views
from .views import *
app_name = 'myapp'
urlpatterns = [ 
    # path('', index, name='index'),
    path('obout_me', obout_me, name='obout_me'),
    path('about', about, name='about'),  
    
    # lab2
    path('', homepage),
    path('create_customer/', CustomerCreate.as_view(), name="create_customer"),
    path('<int:pk>/update_customer/', CustomerUpdate.as_view()),
    path('<int:pk>/delete_customer/', CustomerDelete.as_view()),
    path('create_product/', ProductCreate.as_view(), name="create_product"),
    path('<int:pk>/update_product/', ProductUpdate.as_view()),
    path('<int:pk>/delete_product/', ProductDelete.as_view()),
    path('create_order/', OrderCreate.as_view(), name="create_order"),
    path('<int:pk>/update_order/', OrderUpdate.as_view(), name="update_order"),
    path('<int:pk>/delete_order/', OrderDelete.as_view()),  
    
    # 3 задание 
    path('product_list/<int:id_user>/<str:period>/', product_list),      
    
    path('product/<int:pk_prod>/form_image/', product_add_image, name='product_upload_image'),  
    
] 

django/lesson_1/myapp/models.py
from django.db import models

# Create your models here.

# class User(models.Model):
#     name = models.CharField(max_length=100)
#     email = models.EmailField()
#     password = models.CharField(max_length=100)
#     age = models.IntegerField()
    
#     def __str__(self):
#         return f'Username: {self.name}, email: {self.email}, age {self.age}'
    
# class Product(models.Model):
#     name = models.CharField(max_length=100)
#     price = models.DecimalField(max_digits=8, decimal_places=2)
#     decription = models.TextField()
#     image = models.ImageField(upload_to='products/')
    
# class Order(models.Model):
#     customer = models.ForeignKey(User, on_delete=models.CASCADE)
#     products = models.ManyToManyField(Product)
#     date_ordered = models.DateTimeField(auto_now_add=True)#автоустановка
#     total_price = models.DecimalField(max_digits=8, decimal_places=2)# стандарнтная запись

class Customer(models.Model):
    # Поля модели клиента
    name = models.CharField(max_length=200)
    email = models.EmailField()
    phone_number = models.IntegerField()
    address = models.TextField()
    registration_date = models.DateTimeField(auto_now_add=True)#'client registration date'

    def __str__(self):
        return self.name

class Product(models.Model): 
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveSmallIntegerField()
    date_added = models.DateField(auto_now_add=True)
    photo = models.CharField(max_length=255, default = "")
    # photo = models.ImageField(upload_to="product_photos/") # Adding Image Field

    def __str__(self):
        return self.name

class Order(models.Model):
    # Связывание полей между моделями заказа и клиента
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    # Связующее поле между моделью заказа и моделью товара
    good = models.ManyToManyField(Product)

    # Другие поля модели заказа
    order_total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    # order_date = models.DateTimeField(auto_now_add=True)#'order placement date'
    order_date = models.DateTimeField()#'order placement date'

    def __str__(self):
        return f'{self.customer} - {self.id}'
     

django/lesson_1/myapp/forms.py
import datetime
from django import forms


# очень простая форма
class ImageForm(forms.Form):
    name = forms.CharField(max_length=50)
    image_l = forms.ImageField(required = True)

django/lesson_1/myapp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse,Http404
from django.core.files.storage import FileSystemStorage
from django.utils import timezone 


from .forms import ImageForm


import logging

logger = logging.getLogger(__name__)

# def index(request):
#     logger.info('index page accessed')
#     return HttpResponse("HelW")
 
def index(request): 
    logger.debug('index page accessed')
    html_text = """
        <h1>main Vindow</h1>
        <p>la la la </p>
        <p>all good</p>
    """
    return render(request, 'index.html', {'html_text': html_text})

def obout_me(request):
    # Multiline text variable with HTML layout
    logger.debug('obout_me page accessed')
    html_text = """
        <h1>PK</h1>
        <p> </p>
        <p>  </p>
    """
    return render(request, 'obout_me.html', {'html_text': html_text})


def about(request):
    try:
        result = 1/0
    except Exception as e:
        logger.exception(f'Error in ab page{e}')
        return HttpResponse(" Error ")
    else:
        logger.debug('ab page access')
    return HttpResponse("ab us")



# lab2

from .models import *
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

def homepage(request):
    context = {
        'customers': Customer.objects.all(),
        'products': Product.objects.all(),
       'orders': Order.objects.all(),
    }
    return render(request, 'homepage.html', context)

class CustomerCreate(CreateView):
    model = Customer
    fields = ['name', 'email', 'phone_number', 'address']
    success_url = '/'

class CustomerUpdate(UpdateView):
    model = Customer
    fields = ['name', 'email', 'phone_number', 'address']
    template_name_suffix = '_update_form'
    success_url = '/'

class CustomerDelete(DeleteView):
    model = Customer
    success_url = '/'

class ProductCreate(CreateView):
    model = Product
    fields = ['name', 'description', 'price', 'quantity']
    success_url = '/'

class ProductUpdate(UpdateView):
    model = Product
    fields = ['name', 'description', 'price', 'quantity']
    template_name_suffix = '_update_form'
    success_url = '/'

class ProductDelete(DeleteView):
    model = Product
    success_url = '/'

class OrderCreate(CreateView):
    model = Order
    fields = ['good', 'order_total_amount']
    success_url = '/'

class OrderUpdate(UpdateView):
    model = Order
    fields = ['good', 'order_total_amount']
    template_name_suffix = '_update_form'
    success_url = '/'

class OrderDelete(DeleteView):
    model = Order
    success_url = '/'
    




# http://127.O.O.1:8000/product_list/42/week/
def product_list(request,id_user, period):
    now = timezone.now()
    if period == 'week':
        start_date = now - timezone.timedelta(days=7)
    elif period == 'month':
        start_date = now - timezone.timedelta(days=30)
    elif period == 'year':
        start_date = now - timezone.timedelta(days=365)
    else:
        raise ValueError('Invalid period')
    
    try:
        cur_customer = Customer.objects.get(pk=id_user)
        # context = {'customer': customer}        
    except Customer.DoesNotExist:
        raise Http404("Customer does not exist")

    # customer_orders = Order.objects.filter(customer=request.user, order_date__gte=start_date)
    customer_orders = Order.objects.filter(customer=cur_customer, order_date__gte=start_date)
    products = Product.objects.filter(order__in=customer_orders).distinct()

    return render(request, 'product_list.html', {'cur_customer': cur_customer,'products': products,'customer_orders':customer_orders})

# pk - первичный ключ
# http://127.0.0.1:8000/product/4/form_image/
def product_add_image(request, pk_prod):
    # загрузка продукта
    try:
        cur_product = Product.objects.get(pk=pk_prod)
        # context = {'cur_product': cur_product}        
    except Customer.DoesNotExist:
        raise Http404("Customer does not exist")
    logger.info('user getted')
    
    if request.method == 'POST':
        logger.info('image POST')
        # form = ImageForm(request.POST, request.FILES)
        form = ImageForm(request.POST,request.FILES)
        logger.info('request.FILES')
        if form.is_valid():
            logger.info('image'+form.cleaned_data['image_l'].name)
        # image = form['image']
            image_ll = form.cleaned_data['image_l']
            logger.info('igm  '+image_ll.name)
            
            fs = FileSystemStorage()# работа с файловой системой
            fs.save(image_ll.name, image_ll)
            
            cur_product.photo = image_ll.name
            cur_product.save()
        else:
            logger.info('not valid')
            
        # form = ImageForm()
        return render(request, 'image_form_product.html', {'form':form,'cur_product': cur_product})


    else: 
        form = ImageForm()
        return render(request, 'image_form_product.html', {'form':form,'cur_product': cur_product})
            
        





    

django/lesson_1/myapp/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyApp</title>
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <!-- Header content here -->
    </header>
    <main>
        {% block body %}{% endblock %}
    </main>
    <footer>
        <!-- Footer content here -->
    </footer>
</body>
</html>

django/lesson_1/myapp/templates/customer_update_form.html
{% extends 'base.html' %}
{% block head %}
   {{ form.media }}
{% endblock %}

{% block body %}
<h1>Edit customer</h1>
<form method='post' action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save changes' class='btn btn-primary' />
</form>
{% endblock %}

django/lesson_1/myapp/templates/homepage.html
{% extends 'base.html' %}
{% block body %}
<h1>Customers</h1>
{% if customers %}
    <table>
        <tr><th>Name</th><th>Email</th><th>Phone Number</th><th>Address</th></tr>
        {% for customer in customers %}
            <tr><td>{{ customer.name }}</td><td>{{ customer.email }}</td><td>{{ customer.phone_number }}</td><td>{{ customer.address }}</td></tr>
        {% endfor %}
    </table>
{% else %}
    <p>No Customers found.</p>
{% endif %}

<br />

<h1>Products</h1>
{% if products %}
    <table>
        <tr><th>Name</th><th>Description</th><th>Price</th><th>Quantity</th><th>Date Added</th></tr>
        {% for product in products %}
            <tr><td>{{ product.name }}</td><td>{{ product.description|slice:"0:50" }}...</td><td>{{ product.price }}</td><td>{{ product.quantity }}</td><td>{{ product.date_added }}</td></tr>
        {% endfor %}
    </table>
{% else %}
    <p>No Products found.</p>
{% endif %}

<br />

<h1>Orders</h1>
{% if orders %}
    <table>
        <tr><th>ID</th><th>Customer Name</th><th>Total Amount</th><th>Placed Date</th></tr>
        {% for order in orders %}
            <tr><td><a href="{% url 'myapp:update_order' pk=order.pk %}">{{ order.id }}</a></td><td>{{ order.customer }}</td><td>{{ order.order_total_amount }}</td><td>{{ order.order_date }}</td></tr>
        {% endfor %}
    </table>
{% else %}
    <p>No Orders found.</p>
{% endif %}

<div style="text-align: center; margin-top: 2em;">
    <a href="{% url 'myapp:create_customer' %}">Add new customer</a> 
    <a href="{% url 'myapp:create_product' %}">Add new product</a>  
    <a href="{% url 'myapp:create_order' %}">Place new order</a></div>
                   
{% endblock %}

django/lesson_1/myapp/templates/image_form_product.html
{% extends 'base.html' %}
{% block body %}
<h2>загрузка изображения для продукта "{{cur_product.name }}"</h2>
<div>{{cur_product.image }}</div>


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_div }}
    <input type="submit" value="Отправить">
</form> 
{% endblock %}

django/lesson_1/myapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>main</title>
</head>
<body>
    {{ html_text|safe   }}
    <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem placeat error fugit eum illum fugiat eveniet, ullam sit</p>
</body>
</html> 

django/lesson_1/myapp/templates/obout_me.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>obout_me</title>
</head>
<body>
    {{ html_text|safe }}
    
</body>
</html> 

django/lesson_1/myapp/templates/order_update_form.html
{% extends 'base.html' %}
{% block head %}
   {{ form.media }}
{% endblock %}

{% block body %}
<h1>Order #{{ object.id }} - Edit details</h1>
<form method='post' action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='hidden' name='pk' value='{{ object.id }}'/>
    <input type='submit' value='Save changes' class='btn btn-primary' />
</form>
{% endblock %}

django/lesson_1/myapp/templates/product_list.html
<h1>продукты</h1>
<ul>
{% for product in products %}
    <li>{{ product.name }}</li>
{% empty %}
    <li>Вы ничего не добавили</li>
{% endfor %}
</ul>

<h2>Даты заказов пользователя <br>
    {{cur_customer.name}}, {{cur_customer.email}}</h2>
<ul>
    {% for order in customer_orders %}
        <li>{{ order.order_date }}</li>
    {% empty %}
        <li>Вы ничего не добавили</li>
    {% endfor %}
</ul>

django/lesson_1/myapp/templates/product_update_form.html
{% extends 'base.html' %}
{% block head %}
    {{ form.media }}
{% endblock %}

{% block body %}
<h1>Edit product</h1>
<form method='post' action=".">
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Save changes' class='btn btn-primary' />
</form>
{% endblock %}